// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdO81meQe2Lmvl35MBVNUS9vvAlg5Ipps',
    appId: '1:467140315243:web:08c01ad394781d5b5c892e',
    messagingSenderId: '467140315243',
    projectId: 'fl-firebase-bfb22',
    authDomain: 'fl-firebase-bfb22.firebaseapp.com',
    storageBucket: 'fl-firebase-bfb22.firebasestorage.app',
    measurementId: 'G-0L266DT5Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8USPzFwfy7QlATpUKn41TUDT2D5SR-YQ',
    appId: '1:467140315243:android:94347054b06b8f935c892e',
    messagingSenderId: '467140315243',
    projectId: 'fl-firebase-bfb22',
    storageBucket: 'fl-firebase-bfb22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaXKmdbd2uofwZC9nQuCyaX6hhjor6L8c',
    appId: '1:467140315243:ios:5f389c1d0e278e325c892e',
    messagingSenderId: '467140315243',
    projectId: 'fl-firebase-bfb22',
    storageBucket: 'fl-firebase-bfb22.firebasestorage.app',
    iosBundleId: 'com.example.btludptdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaXKmdbd2uofwZC9nQuCyaX6hhjor6L8c',
    appId: '1:467140315243:ios:5f389c1d0e278e325c892e',
    messagingSenderId: '467140315243',
    projectId: 'fl-firebase-bfb22',
    storageBucket: 'fl-firebase-bfb22.firebasestorage.app',
    iosBundleId: 'com.example.btludptdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdO81meQe2Lmvl35MBVNUS9vvAlg5Ipps',
    appId: '1:467140315243:web:68ca41fe89a953745c892e',
    messagingSenderId: '467140315243',
    projectId: 'fl-firebase-bfb22',
    authDomain: 'fl-firebase-bfb22.firebaseapp.com',
    storageBucket: 'fl-firebase-bfb22.firebasestorage.app',
    measurementId: 'G-E75P4D5JYS',
  );
}
